use_frameworks!

platform :ios, '11.0'

target 'ASCamera_Example' do
  pod 'ASCamera', :path => '../'

  target 'ASCamera_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
